# Generated by Django 5.2.3 on 2025-07-01 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_is_listed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_deleted',
        ),
    ]
