# Generated by Django 5.2.3 on 2025-07-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_category_is_deleted_category_is_listed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
