# Generated by Django 5.2.3 on 2025-07-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
