# Generated by Django 5.2.3 on 2025-07-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_cartitem_unique_together_cartitem_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='variant_name',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='volume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
