# Generated by Django 5.2.3 on 2025-07-19 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_productvariant_variant_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
