# Generated by Django 5.2.3 on 2025-07-19 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_productvariant_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
