# Generated by Django 5.2.3 on 2025-07-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
