# Generated by Django 5.2.3 on 2025-07-21 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_productimage_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='variant',
        ),
    ]
