# Generated by Django 5.2.3 on 2025-07-21 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_productvariant_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='price',
        ),
    ]
