# Generated by Django 5.2.3 on 2025-07-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_product_discount_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_percent',
        ),
    ]
