# Generated by Django 5.2.3 on 2025-07-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_remove_product_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='CategoryOffer',
        ),
    ]
