# Generated by Django 5.1.7 on 2025-08-19 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
