"""
Django settings for babymuse project.

Generated by 'django-admin startproject' using Django 5.2.3.
"""

# ---------------------------------------
# 0️⃣ Core imports
# ---------------------------------------
from decouple import config
from pathlib import Path
import os
import logging


# ---------------------------------------
# 1️⃣ Base config
# ---------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# Custom User model
AUTH_USER_MODEL = 'user.CustomUser'

# Secret key and debug
SECRET_KEY = config("SECRET_KEY")
DEBUG =True

# Allowed hosts
ALLOWED_HOSTS = ['*']

# Logging
logging.basicConfig(level=logging.DEBUG)

# ---------------------------------------
# 2️⃣ Installed apps
# ---------------------------------------
INSTALLED_APPS = [
    'user',
    'admin_panel',
    'shop',
    'orders',
    'core',
    'cloudinary',
    'cloudinary_storage',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
]

# ---------------------------------------
# 3️⃣ Cloudinary config
# ---------------------------------------
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config("CLOUD_NAME"),
    'API_KEY': config("API_KEY"),
    'API_SECRET': config("API_SECRET"),
}

# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"

# ---------------------------------------
# 4️⃣ Middleware
# ---------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

# ---------------------------------------
# 5️⃣ URLs and templates
# ---------------------------------------
ROOT_URLCONF = 'babymuse.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'core.context_processors.shared_counts',
            ],
        },
    },
]

WSGI_APPLICATION = 'babymuse.wsgi.application'

# ---------------------------------------
# 6️⃣ Database
# ---------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config("DB_NAME"),
        'USER': config("DB_USER"),
        'PASSWORD': config("DB_PASSWORD"),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}

# ---------------------------------------
# 7️⃣ Payments
# ---------------------------------------
RAZORPAY_KEY_ID = "rzp_test_pG3gGzM1UjS5rN"
RAZORPAY_KEY_SECRET = "doHMf3PNkXg5Dbsyn1T2mqUq"

# ---------------------------------------
# 8️⃣ Password validators
# ---------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ---------------------------------------
# 9️⃣ Internationalization
# ---------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ---------------------------------------
# 10️⃣ Static & media
# ---------------------------------------
STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------
# 11️⃣ Email
# ---------------------------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="tpnafeesath90@gmail.com")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = 'admin@babymuse.com'

# ---------------------------------------
# 12️⃣ Authentication & social login
# ---------------------------------------
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config("SOCIAL_AUTH_GOOGLE_OAUTH2_KEY", default="")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config("SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET", default="")

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/user/login/'
