# Generated by Django 5.2.3 on 2025-07-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_is_returned_orderitem_return_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='return_requested_at',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_return_requested',
            field=models.BooleanField(default=False),
        ),
    ]
